# Production Profile Configuration
# Oracle MCP Server - Enhanced for production deployment

spring:
  profiles:
    active: prod
  
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      
      # Oracle-specific optimizations
      data-source-properties:
        oracle.net.CONNECT_TIMEOUT: 60000
        oracle.jdbc.ReadTimeout: 60000
        oracle.jdbc.J2EE13Compliant: true
        oracle.jdbc.implicitStatementCacheSize: 20
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

# Logging Configuration for Production
logging:
  level:
    root: WARN
    com.deepai.mcpserver: INFO
    oracle.jdbc: WARN
    org.springframework.security: WARN
    org.springframework.ai: INFO
  
  file:
    name: logs/oracle-mcp-server.log
  
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# Actuator Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms

# Oracle Configuration for Production
oracle:
  features:
    detection:
      enabled: true
    cache:
      ttl: 3600
    tools:
      core:
        enabled: true
        count: 25
      analytics:
        enabled: true
        count: 20
      ai:
        enabled: true
        count: 10
      enterprise:
        enabled: false

# MCP Configuration for Production
mcp:
  tools:
    exposure: public
  transport: stdio

# Security Configuration
security:
  require-ssl: false  # Enable in production with proper certificates
  enable-csrf: false  # MCP typically doesn't need CSRF protection

# Spring Security User Configuration
spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
